BEGIN;


CREATE TABLE IF NOT EXISTS public.auth_group
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_group_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_name_key UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS public.auth_group_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    group_id integer NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id)
);

CREATE TABLE IF NOT EXISTS public.auth_permission
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT auth_permission_pkey PRIMARY KEY (id),
    CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename)
);

CREATE TABLE IF NOT EXISTS public.authtoken_token
(
    key character varying(40) COLLATE pg_catalog."default" NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT authtoken_token_pkey PRIMARY KEY (key),
    CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.django_admin_log
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    action_time timestamp with time zone NOT NULL,
    object_id text COLLATE pg_catalog."default",
    object_repr character varying(200) COLLATE pg_catalog."default" NOT NULL,
    action_flag smallint NOT NULL,
    change_message text COLLATE pg_catalog."default" NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_content_type
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    app_label character varying(100) COLLATE pg_catalog."default" NOT NULL,
    model character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT django_content_type_pkey PRIMARY KEY (id),
    CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model)
);

CREATE TABLE IF NOT EXISTS public.django_migrations
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    app character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    applied timestamp with time zone NOT NULL,
    CONSTRAINT django_migrations_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.django_session
(
    session_key character varying(40) COLLATE pg_catalog."default" NOT NULL,
    session_data text COLLATE pg_catalog."default" NOT NULL,
    expire_date timestamp with time zone NOT NULL,
    CONSTRAINT django_session_pkey PRIMARY KEY (session_key)
);

CREATE TABLE IF NOT EXISTS public.info_assign
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    class_id_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    course_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    teacher_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT info_assign_pkey PRIMARY KEY (id),
    CONSTRAINT info_assign_course_id_class_id_id_teacher_id_fd958bf0_uniq UNIQUE (course_id, class_id_id, teacher_id)
);

CREATE TABLE IF NOT EXISTS public.info_assigntime
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    period character varying(50) COLLATE pg_catalog."default" NOT NULL,
    day character varying(15) COLLATE pg_catalog."default" NOT NULL,
    assign_id bigint NOT NULL,
    CONSTRAINT info_assigntime_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.info_attendance
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    date date NOT NULL,
    status boolean NOT NULL,
    attendanceclass_id bigint NOT NULL,
    course_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    student_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT info_attendance_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.info_attendanceclass
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    date date NOT NULL,
    status integer NOT NULL,
    assign_id bigint NOT NULL,
    CONSTRAINT info_attendanceclass_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.info_attendancerange
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    start_date date NOT NULL,
    end_date date NOT NULL,
    CONSTRAINT info_attendancerange_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.info_attendancetotal
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    course_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    student_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT info_attendancetotal_pkey PRIMARY KEY (id),
    CONSTRAINT info_attendancetotal_student_id_course_id_f5461a1c_uniq UNIQUE (student_id, course_id)
);

CREATE TABLE IF NOT EXISTS public.info_class
(
    id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    section character varying(100) COLLATE pg_catalog."default" NOT NULL,
    sem integer NOT NULL,
    dept_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT info_class_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.info_course
(
    id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    shortname character varying(50) COLLATE pg_catalog."default" NOT NULL,
    dept_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT info_course_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.info_dept
(
    id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT info_dept_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.info_marks
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    marks1 integer NOT NULL,
    studentcourse_id bigint NOT NULL,
    CONSTRAINT info_marks_pkey PRIMARY KEY (id),
    CONSTRAINT info_marks_studentcourse_id_name_1091fffa_uniq UNIQUE (studentcourse_id, name)
);

CREATE TABLE IF NOT EXISTS public.info_marksclass
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(50) COLLATE pg_catalog."default" NOT NULL,
    status boolean NOT NULL,
    assign_id bigint NOT NULL,
    CONSTRAINT info_marksclass_pkey PRIMARY KEY (id),
    CONSTRAINT info_marksclass_assign_id_name_e0207692_uniq UNIQUE (assign_id, name)
);

CREATE TABLE IF NOT EXISTS public.info_student
(
    "USN" character varying(100) COLLATE pg_catalog."default" NOT NULL,
    name character varying(200) COLLATE pg_catalog."default" NOT NULL,
    sex character varying(50) COLLATE pg_catalog."default" NOT NULL,
    class_id_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    user_id bigint,
    "DOB" date NOT NULL,
    CONSTRAINT info_student_pkey PRIMARY KEY ("USN"),
    CONSTRAINT info_student_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.info_studentcourse
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    course_id character varying(50) COLLATE pg_catalog."default" NOT NULL,
    student_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT info_studentcourse_pkey PRIMARY KEY (id),
    CONSTRAINT info_studentcourse_student_id_course_id_96c683ba_uniq UNIQUE (student_id, course_id)
);

CREATE TABLE IF NOT EXISTS public.info_teacher
(
    id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    sex character varying(50) COLLATE pg_catalog."default" NOT NULL,
    dept_id character varying(100) COLLATE pg_catalog."default" NOT NULL,
    "DOB" date NOT NULL,
    user_id bigint,
    CONSTRAINT info_teacher_pkey PRIMARY KEY (id),
    CONSTRAINT info_teacher_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.info_user
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    password character varying(128) COLLATE pg_catalog."default" NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) COLLATE pg_catalog."default" NOT NULL,
    first_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    last_name character varying(150) COLLATE pg_catalog."default" NOT NULL,
    email character varying(254) COLLATE pg_catalog."default" NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    CONSTRAINT info_user_pkey PRIMARY KEY (id),
    CONSTRAINT info_user_username_key UNIQUE (username)
);

CREATE TABLE IF NOT EXISTS public.info_user_groups
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id bigint NOT NULL,
    group_id integer NOT NULL,
    CONSTRAINT info_user_groups_pkey PRIMARY KEY (id),
    CONSTRAINT info_user_groups_user_id_group_id_1b352364_uniq UNIQUE (user_id, group_id)
);

CREATE TABLE IF NOT EXISTS public.info_user_user_permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    user_id bigint NOT NULL,
    permission_id integer NOT NULL,
    CONSTRAINT info_user_user_permissions_pkey PRIMARY KEY (id),
    CONSTRAINT info_user_user_permissions_user_id_permission_id_86ac821e_uniq UNIQUE (user_id, permission_id)
);

ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_permission_id_84c5c92e
    ON public.auth_group_permissions(permission_id);


ALTER TABLE IF EXISTS public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_group_permissions_group_id_b120cbf9
    ON public.auth_group_permissions(group_id);


ALTER TABLE IF EXISTS public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS auth_permission_content_type_id_2f476e4b
    ON public.auth_permission(content_type_id);


ALTER TABLE IF EXISTS public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk FOREIGN KEY (user_id)
    REFERENCES public.info_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS authtoken_token_user_id_key
    ON public.authtoken_token(user_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id)
    REFERENCES public.django_content_type (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_content_type_id_c4bce8eb
    ON public.django_admin_log(content_type_id);


ALTER TABLE IF EXISTS public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk FOREIGN KEY (user_id)
    REFERENCES public.info_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS django_admin_log_user_id_c564eba6
    ON public.django_admin_log(user_id);


ALTER TABLE IF EXISTS public.info_assign
    ADD CONSTRAINT info_assign_class_id_id_97445caa_fk_info_class_id FOREIGN KEY (class_id_id)
    REFERENCES public.info_class (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS info_assign_class_id_id_97445caa
    ON public.info_assign(class_id_id);


ALTER TABLE IF EXISTS public.info_assign
    ADD CONSTRAINT info_assign_course_id_50da791d_fk_info_course_id FOREIGN KEY (course_id)
    REFERENCES public.info_course (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS info_assign_course_id_50da791d_like
    ON public.info_assign(course_id);


ALTER TABLE IF EXISTS public.info_assign
    ADD CONSTRAINT info_assign_teacher_id_4cc729a9_fk FOREIGN KEY (teacher_id)
    REFERENCES public.info_teacher (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS info_assign_teacher_id_4cc729a9
    ON public.info_assign(teacher_id);


ALTER TABLE IF EXISTS public.info_assigntime
    ADD CONSTRAINT info_assigntime_assign_id_dea972e8_fk FOREIGN KEY (assign_id)
    REFERENCES public.info_assign (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS info_assigntime_assign_id_dea972e8
    ON public.info_assigntime(assign_id);


ALTER TABLE IF EXISTS public.info_attendance
    ADD CONSTRAINT info_attendance_attendanceclass_id_165ae557_fk FOREIGN KEY (attendanceclass_id)
    REFERENCES public.info_attendanceclass (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS info_attendance_attendanceclass_id_165ae557
    ON public.info_attendance(attendanceclass_id);


ALTER TABLE IF EXISTS public.info_attendance
    ADD CONSTRAINT info_attendance_course_id_862fb2a9_fk_info_course_id FOREIGN KEY (course_id)
    REFERENCES public.info_course (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS info_attendance_course_id_862fb2a9_like
    ON public.info_attendance(course_id);


ALTER TABLE IF EXISTS public.info_attendance
    ADD CONSTRAINT "info_attendance_student_id_a3848ef5_fk_info_student_USN" FOREIGN KEY (student_id)
    REFERENCES public.info_student ("USN") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS info_attendance_student_id_a3848ef5
    ON public.info_attendance(student_id);


ALTER TABLE IF EXISTS public.info_attendanceclass
    ADD CONSTRAINT info_attendanceclass_assign_id_8241361c_fk FOREIGN KEY (assign_id)
    REFERENCES public.info_assign (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS info_attendanceclass_assign_id_8241361c
    ON public.info_attendanceclass(assign_id);


ALTER TABLE IF EXISTS public.info_attendancetotal
    ADD CONSTRAINT info_attendancetotal_course_id_d7c45376_fk_info_course_id FOREIGN KEY (course_id)
    REFERENCES public.info_course (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS info_attendancetotal_course_id_d7c45376_like
    ON public.info_attendancetotal(course_id);


ALTER TABLE IF EXISTS public.info_attendancetotal
    ADD CONSTRAINT "info_attendancetotal_student_id_47e719b1_fk_info_student_USN" FOREIGN KEY (student_id)
    REFERENCES public.info_student ("USN") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS info_attendancetotal_student_id_47e719b1_like
    ON public.info_attendancetotal(student_id);


ALTER TABLE IF EXISTS public.info_class
    ADD CONSTRAINT info_class_dept_id_eac78ba6_fk_info_dept_id FOREIGN KEY (dept_id)
    REFERENCES public.info_dept (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS info_class_dept_id_eac78ba6_like
    ON public.info_class(dept_id);


ALTER TABLE IF EXISTS public.info_course
    ADD CONSTRAINT info_course_dept_id_8783e216_fk_info_dept_id FOREIGN KEY (dept_id)
    REFERENCES public.info_dept (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS info_course_dept_id_8783e216_like
    ON public.info_course(dept_id);


ALTER TABLE IF EXISTS public.info_marks
    ADD CONSTRAINT info_marks_studentcourse_id_9db4f113_fk FOREIGN KEY (studentcourse_id)
    REFERENCES public.info_studentcourse (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS info_marks_studentcourse_id_9db4f113
    ON public.info_marks(studentcourse_id);


ALTER TABLE IF EXISTS public.info_marksclass
    ADD CONSTRAINT info_marksclass_assign_id_06c0e888_fk FOREIGN KEY (assign_id)
    REFERENCES public.info_assign (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS info_marksclass_assign_id_06c0e888
    ON public.info_marksclass(assign_id);


ALTER TABLE IF EXISTS public.info_student
    ADD CONSTRAINT info_student_class_id_id_49fe47c8_fk_info_class_id FOREIGN KEY (class_id_id)
    REFERENCES public.info_class (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS info_student_class_id_id_49fe47c8
    ON public.info_student(class_id_id);


ALTER TABLE IF EXISTS public.info_student
    ADD CONSTRAINT info_student_user_id_3ec39602_fk FOREIGN KEY (user_id)
    REFERENCES public.info_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS info_student_user_id_key
    ON public.info_student(user_id);


ALTER TABLE IF EXISTS public.info_studentcourse
    ADD CONSTRAINT info_studentcourse_course_id_2aac8b3b_fk_info_course_id FOREIGN KEY (course_id)
    REFERENCES public.info_course (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS info_studentcourse_course_id_2aac8b3b_like
    ON public.info_studentcourse(course_id);


ALTER TABLE IF EXISTS public.info_studentcourse
    ADD CONSTRAINT "info_studentcourse_student_id_824a5a25_fk_info_student_USN" FOREIGN KEY (student_id)
    REFERENCES public.info_student ("USN") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS info_studentcourse_student_id_824a5a25_like
    ON public.info_studentcourse(student_id);


ALTER TABLE IF EXISTS public.info_teacher
    ADD CONSTRAINT info_teacher_dept_id_e65acdf7_fk_info_dept_id FOREIGN KEY (dept_id)
    REFERENCES public.info_dept (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS info_teacher_dept_id_e65acdf7
    ON public.info_teacher(dept_id);


ALTER TABLE IF EXISTS public.info_teacher
    ADD CONSTRAINT info_teacher_user_id_1ed88589_fk FOREIGN KEY (user_id)
    REFERENCES public.info_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS info_teacher_user_id_key
    ON public.info_teacher(user_id);


ALTER TABLE IF EXISTS public.info_user_groups
    ADD CONSTRAINT info_user_groups_group_id_40dffdbb_fk_auth_group_id FOREIGN KEY (group_id)
    REFERENCES public.auth_group (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS info_user_groups_group_id_40dffdbb
    ON public.info_user_groups(group_id);


ALTER TABLE IF EXISTS public.info_user_groups
    ADD CONSTRAINT info_user_groups_user_id_583ab83a_fk FOREIGN KEY (user_id)
    REFERENCES public.info_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS info_user_groups_user_id_583ab83a
    ON public.info_user_groups(user_id);


ALTER TABLE IF EXISTS public.info_user_user_permissions
    ADD CONSTRAINT info_user_user_permi_permission_id_839364f4_fk_auth_perm FOREIGN KEY (permission_id)
    REFERENCES public.auth_permission (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS info_user_user_permissions_permission_id_839364f4
    ON public.info_user_user_permissions(permission_id);


ALTER TABLE IF EXISTS public.info_user_user_permissions
    ADD CONSTRAINT info_user_user_permissions_user_id_ffc10b58_fk FOREIGN KEY (user_id)
    REFERENCES public.info_user (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX IF NOT EXISTS info_user_user_permissions_user_id_ffc10b58
    ON public.info_user_user_permissions(user_id);

END;